# PyCaret for Feature Engineering and Model Selection

### Requires python 3.9, 3.10 or 3.11
### Nof fully compatible with CatBoost

In [1]:
# pip install pycaret

In [ ]:
# pip install catboost lgbm xgboost

In [ ]:
# importing libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from pycaret.classification import *

In [4]:
# importing the data
adult = pd.read_csv("adult.csv")
adult.head()

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K

# PyCaret

In [5]:
# PyCaret full workflow on original adult data
# NOTE: PyCaret expects raw-ish data and handles preprocessing internally

from pycaret.classification import *
from sklearn.model_selection import train_test_split

# train/test split from original dataset
train_pc, test_pc = train_test_split(
    adult,
    test_size=0.2,
    random_state=42,
    stratify=adult["income"]
)

# setup experiment
clf_setup = setup(
    data=train_pc,
    target="income",
    session_id=42,
    fold_strategy="stratifiedkfold",
    fold=5,
    numeric_imputation="median",
    categorical_imputation="mode",
    normalize=False,
    verbose=False
)

# compare top models
top_models = compare_models(n_select=3)

# tune the best one
tuned_model = tune_model(top_models[0])

# blend top models
blended_model = blend_models(estimator_list=top_models)

# stack top models
stacked_model = stack_models(estimator_list=top_models)

# finalize chosen model
final_model = finalize_model(stacked_model)

# predict on held-out test set
preds = predict_model(final_model, data=test_pc)

# show results
preds.head()

Initiated  . . . . . . . . . . . . . . . . . .                   17:43:00
Status     . . . . . . . . . . . . . . . . . .  Searching Hyperparameters
Estimator  . . . . . . . . . . . . . . . . . .        CatBoost Classifier

Processing:   0%|          | 0/7 [00:00<?, ?it/s]

Fitting 5 folds for each of 10 candidates, totalling 50 fits

ValueError:
All the 50 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "/opt/anaconda3/envs/pyenv311/lib/python3.11/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/opt/anaconda3/envs/pyenv311/lib/python3.11/site-packages/pycaret/internal/pipeline.py", line 279, in fit
    clone(self.steps[-1][1]), X, y, **last_step_params["fit"]
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/pyenv311/lib/python3.11/site-packages/sklearn/base.py", line 91, in clone
    return _clone_parametrized(estimator, safe=safe)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/pyenv311/lib/python3.11/site-packages/sklearn/base.py", line 138, in _clone_parametrized
    raise RuntimeError(
RuntimeError: Cannot clone object CatBoostClassifier(border_count=254, depth=4, eta=1e-06, l2_leaf_reg=4, n_estimators=280, random_state=42, random_strength=0.0, task_type='CPU', verbose=False), as the constructor either does not set or modifies parameter n_estimators

--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "/opt/anaconda3/envs/pyenv311/lib/python3.11/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/opt/anaconda3/envs/pyenv311/lib/python3.11/site-packages/pycaret/internal/pipeline.py", line 279, in fit
    clone(self.steps[-1][1]), X, y, **last_step_params["fit"]
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/pyenv311/lib/python3.11/site-packages/sklearn/base.py", line 91, in clone
    return _clone_parametrized(estimator, safe=safe)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/pyenv311/lib/python3.11/site-packages/sklearn/base.py", line 138, in _clone_parametrized
    raise RuntimeError(
RuntimeError: Cannot clone object CatBoostClassifier(border_count=254, depth=3, eta=0.0001, l2_leaf_reg=2, n_estimators=210, random_state=42, random_strength=0.8, task_type='CPU', verbose=False), as the constructor either does not set or modifies parameter n_estimators

--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "/opt/anaconda3/envs/pyenv311/lib/python3.11/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/opt/anaconda3/envs/pyenv311/lib/python3.11/site-packages/pycaret/internal/pipeline.py", line 279, in fit
    clone(self.steps[-1][1]), X, y, **last_step_params["fit"]
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/pyenv311/lib/python3.11/site-packages/sklearn/base.py", line 91, in clone
    return _clone_parametrized(estimator, safe=safe)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/pyenv311/lib/python3.11/site-packages/sklearn/base.py", line 138, in _clone_parametrized
    raise RuntimeError(
RuntimeError: Cannot clone object CatBoostClassifier(border_count=254, depth=3, eta=0.01, l2_leaf_reg=9, n_estimators=200, random_state=42, random_strength=0.1, task_type='CPU', verbose=False), as the constructor either does not set or modifies parameter n_estimators

--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "/opt/anaconda3/envs/pyenv311/lib/python3.11/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/opt/anaconda3/envs/pyenv311/lib/python3.11/site-packages/pycaret/internal/pipeline.py", line 279, in fit
    clone(self.steps[-1][1]), X, y, **last_step_params["fit"]
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/pyenv311/lib/python3.11/site-packages/sklearn/base.py", line 91, in clone
    return _clone_parametrized(estimator, safe=safe)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/pyenv311/lib/python3.11/site-packages/sklearn/base.py", line 138, in _clone_parametrized
    raise RuntimeError(
RuntimeError: Cannot clone object CatBoostClassifier(border_count=254, depth=1, eta=0.5, l2_leaf_reg=9, n_estimators=90, random_state=42, random_strength=0.4, task_type='CPU', verbose=False), as the constructor either does not set or modifies parameter n_estimators

--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "/opt/anaconda3/envs/pyenv311/lib/python3.11/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/opt/anaconda3/envs/pyenv311/lib/python3.11/site-packages/pycaret/internal/pipeline.py", line 279, in fit
    clone(self.steps[-1][1]), X, y, **last_step_params["fit"]
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/pyenv311/lib/python3.11/site-packages/sklearn/base.py", line 91, in clone
    return _clone_parametrized(estimator, safe=safe)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/pyenv311/lib/python3.11/site-packages/sklearn/base.py", line 138, in _clone_parametrized
    raise RuntimeError(
RuntimeError: Cannot clone object CatBoostClassifier(border_count=254, depth=5, eta=0.05, l2_leaf_reg=200, n_estimators=280, random_state=42, random_strength=0.5, task_type='CPU', verbose=False), as the constructor either does not set or modifies parameter n_estimators

--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "/opt/anaconda3/envs/pyenv311/lib/python3.11/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/opt/anaconda3/envs/pyenv311/lib/python3.11/site-packages/pycaret/internal/pipeline.py", line 279, in fit
    clone(self.steps[-1][1]), X, y, **last_step_params["fit"]
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/pyenv311/lib/python3.11/site-packages/sklearn/base.py", line 91, in clone
    return _clone_parametrized(estimator, safe=safe)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/pyenv311/lib/python3.11/site-packages/sklearn/base.py", line 138, in _clone_parametrized
    raise RuntimeError(
RuntimeError: Cannot clone object CatBoostClassifier(border_count=254, depth=2, eta=0.05, l2_leaf_reg=10, n_estimators=30, random_state=42, random_strength=0.0, task_type='CPU', verbose=False), as the constructor either does not set or modifies parameter n_estimators

--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "/opt/anaconda3/envs/pyenv311/lib/python3.11/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/opt/anaconda3/envs/pyenv311/lib/python3.11/site-packages/pycaret/internal/pipeline.py", line 279, in fit
    clone(self.steps[-1][1]), X, y, **last_step_params["fit"]
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/pyenv311/lib/python3.11/site-packages/sklearn/base.py", line 91, in clone
    return _clone_parametrized(estimator, safe=safe)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/pyenv311/lib/python3.11/site-packages/sklearn/base.py", line 138, in _clone_parametrized
    raise RuntimeError(
RuntimeError: Cannot clone object CatBoostClassifier(border_count=254, depth=7, eta=0.005, l2_leaf_reg=5, n_estimators=290, random_state=42, random_strength=0.6, task_type='CPU', verbose=False), as the constructor either does not set or modifies parameter n_estimators

--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "/opt/anaconda3/envs/pyenv311/lib/python3.11/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/opt/anaconda3/envs/pyenv311/lib/python3.11/site-packages/pycaret/internal/pipeline.py", line 279, in fit
    clone(self.steps[-1][1]), X, y, **last_step_params["fit"]
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/pyenv311/lib/python3.11/site-packages/sklearn/base.py", line 91, in clone
    return _clone_parametrized(estimator, safe=safe)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/pyenv311/lib/python3.11/site-packages/sklearn/base.py", line 138, in _clone_parametrized
    raise RuntimeError(
RuntimeError: Cannot clone object CatBoostClassifier(border_count=254, depth=10, eta=0.0001, l2_leaf_reg=30, n_estimators=70, random_state=42, random_strength=0.6, task_type='CPU', verbose=False), as the constructor either does not set or modifies parameter n_estimators

--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "/opt/anaconda3/envs/pyenv311/lib/python3.11/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/opt/anaconda3/envs/pyenv311/lib/python3.11/site-packages/pycaret/internal/pipeline.py", line 279, in fit
    clone(self.steps[-1][1]), X, y, **last_step_params["fit"]
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/pyenv311/lib/python3.11/site-packages/sklearn/base.py", line 91, in clone
    return _clone_parametrized(estimator, safe=safe)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/pyenv311/lib/python3.11/site-packages/sklearn/base.py", line 138, in _clone_parametrized
    raise RuntimeError(
RuntimeError: Cannot clone object CatBoostClassifier(border_count=254, depth=3, eta=0.0005, l2_leaf_reg=100, n_estimators=200, random_state=42, random_strength=0.6, task_type='CPU', verbose=False), as the constructor either does not set or modifies parameter n_estimators

--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "/opt/anaconda3/envs/pyenv311/lib/python3.11/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/opt/anaconda3/envs/pyenv311/lib/python3.11/site-packages/pycaret/internal/pipeline.py", line 279, in fit
    clone(self.steps[-1][1]), X, y, **last_step_params["fit"]
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/pyenv311/lib/python3.11/site-packages/sklearn/base.py", line 91, in clone
    return _clone_parametrized(estimator, safe=safe)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/pyenv311/lib/python3.11/site-packages/sklearn/base.py", line 138, in _clone_parametrized
    raise RuntimeError(
RuntimeError: Cannot clone object CatBoostClassifier(border_count=254, depth=2, eta=0.5, l2_leaf_reg=4, n_estimators=130, random_state=42, random_strength=0.0, task_type='CPU', verbose=False), as the constructor either does not set or modifies parameter n_estimators

In [6]:
# PyCaret full workflow on original adult data
# Excluding CatBoost so tune_model() runs cleanly

from pycaret.classification import *
from sklearn.model_selection import train_test_split

# train/test split from original dataset
train_pc, test_pc = train_test_split(
    adult,
    test_size=0.2,
    random_state=42,
    stratify=adult["income"]
)

# setup experiment
clf_setup = setup(
    data=train_pc,
    target="income",
    session_id=42,
    fold_strategy="stratifiedkfold",
    fold=5,
    numeric_imputation="median",
    categorical_imputation="mode",
    normalize=False,
    verbose=False
)

# compare top models, excluding CatBoost
top_models = compare_models(
    n_select=3,
    exclude=["catboost"]
)

# tune the best model
tuned_model = tune_model(top_models[0])

# blend top models
blended_model = blend_models(estimator_list=top_models)

# stack top models
stacked_model = stack_models(estimator_list=top_models)

# finalize chosen model
final_model = finalize_model(stacked_model)

# predict on held-out test set
preds = predict_model(final_model, data=test_pc)

# show results
preds.head()

Fitting 5 folds for each of 10 candidates, totalling 50 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income,prediction_label,prediction_score
40342,54,Private,115602,HS-grad,9,Married-civ-spouse,Other-service,Wife,Black,Female,0,0,40,United-States,<=50K,<=50K,0.8790
47680,28,Local-gov,401886,HS-grad,9,Never-married,Adm-clerical,Other-relative,White,Male,0,0,20,United-States,<=50K,<=50K,0.9642
524,53,Local-gov,139671,Some-college,10,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,50,United-States,<=50K,>50K,0.8242
8508,58,Private,177368,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,3137,0,16,United-States,<=50K,<=50K,0.9571
31692,47,Local-gov,352614,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K,>50K,0.8627

In [8]:
# Show models and parameters clearly

from pprint import pprint

print("Top 3 Models Selected:")
for i, model in enumerate(top_models):
    print(f"\nModel {i+1}: {type(model).__name__}")
    pprint(model.get_params())

print("\nTuned Best Model:")
print(type(tuned_model).__name__)
pprint(tuned_model.get_params())

print("\nStacked Model Structure:")
print(stacked_model)

Top 3 Models Selected:

Model 1: LGBMClassifier
{'boosting_type': 'gbdt',
 'class_weight': None,
 'colsample_bytree': 1.0,
 'importance_type': 'split',
 'learning_rate': 0.1,
 'max_depth': -1,
 'min_child_samples': 20,
 'min_child_weight': 0.001,
 'min_split_gain': 0.0,
 'n_estimators': 100,
 'n_jobs': -1,
 'num_leaves': 31,
 'objective': None,
 'random_state': 42,
 'reg_alpha': 0.0,
 'reg_lambda': 0.0,
 'subsample': 1.0,
 'subsample_for_bin': 200000,
 'subsample_freq': 0}

Model 2: XGBClassifier
{'base_score': None,
 'booster': 'gbtree',
 'callbacks': None,
 'colsample_bylevel': None,
 'colsample_bynode': None,
 'colsample_bytree': None,
 'device': 'cpu',
 'early_stopping_rounds': None,
 'enable_categorical': False,
 'eval_metric': None,
 'feature_types': None,
 'feature_weights': None,
 'gamma': None,
 'grow_policy': None,
 'importance_type': None,
 'interaction_constraints': None,
 'learning_rate': None,
 'max_bin': None,
 'max_cat_threshold': None,
 'max_cat_to_onehot': None,
 'max_delta_step': None,
 'max_depth': None,
 'max_leaves': None,
 'min_child_weight': None,
 'missing': nan,
 'monotone_constraints': None,
 'multi_strategy': None,
 'n_estimators': None,
 'n_jobs': -1,
 'num_parallel_tree': None,
 'objective': 'binary:logistic',
 'random_state': 42,
 'reg_alpha': None,
 'reg_lambda': None,
 'sampling_method': None,
 'scale_pos_weight': None,
 'subsample': None,
 'tree_method': 'auto',
 'validate_parameters': None,
 'verbosity': 0}

Model 3: GradientBoostingClassifier
{'ccp_alpha': 0.0,
 'criterion': 'friedman_mse',
 'init': None,
 'learning_rate': 0.1,
 'loss': 'log_loss',
 'max_depth': 3,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_iter_no_change': None,
 'random_state': 42,
 'subsample': 1.0,
 'tol': 0.0001,
 'validation_fraction': 0.1,
 'verbose': 0,
 'warm_start': False}

Tuned Best Model:
LGBMClassifier
{'boosting_type': 'gbdt',
 'class_weight': None,
 'colsample_bytree': 1.0,
 'importance_type': 'split',
 'learning_rate': 0.1,
 'max_depth': -1,
 'min_child_samples': 20,
 'min_child_weight': 0.001,
 'min_split_gain': 0.0,
 'n_estimators': 100,
 'n_jobs': -1,
 'num_leaves': 31,
 'objective': None,
 'random_state': 42,
 'reg_alpha': 0.0,
 'reg_lambda': 0.0,
 'subsample': 1.0,
 'subsample_for_bin': 200000,
 'subsample_freq': 0}

Stacked Model Structure:
StackingClassifier(cv=5,
                   estimators=[('Light Gradient Boosting Machine',
                                LGBMClassifier(boosting_type='gbdt',
                                               class_weight=None,
                                               colsample_bytree=1.0,
                                               importance_type='split',
                                               learning_rate=0.1, max_depth=-1,
                                               min_child_samples=20,
                                               min_child_weight=0.001,
                                               min_split_gain=0.0,
                                               n_estimators=100, n_jobs=-1,
                                               num_leaves=31, objective=None,
                                               random_state=42, reg_alpha=0.0,
                                               reg...
                                                           validation_fraction=0.1,
                                                           verbose=0,
                                                           warm_start=False))],
                   final_estimator=LogisticRegression(C=1.0, class_weight=None,
                                                      dual=False,
                                                      fit_intercept=True,
                                                      intercept_scaling=1,
                                                      l1_ratio=None,
                                                      max_iter=1000,
                                                      multi_class='auto',
                                                      n_jobs=None, penalty='l2',
                                                      random_state=42,
                                                      solver='lbfgs',
                                                      tol=0.0001, verbose=0,
                                                      warm_start=False),
                   n_jobs=-1, passthrough=False, stack_method='auto',
                   verbose=0)

In [ ]:
# print full details of base and meta models in the stack
print("Base models in stack:\n")
for name, model in stacked_model.estimators:
    print(f"{name}:")
    print(model)
    print()
    
print("Meta model:\n")
print(stacked_model.final_estimator)

Base models in stack:

Light Gradient Boosting Machine:
LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
               random_state=42, reg_alpha=0.0, reg_lambda=0.0, subsample=1.0,
               subsample_for_bin=200000, subsample_freq=0)

Extreme Gradient Boosting:
XGBClassifier(base_score=None, booster='gbtree', callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device='cpu', early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=-1, num_parallel_tree=None, ...)

Gradient Boosting Classifier:
GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='log_loss', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_samples_leaf=1,
                           min_samples_split=2, min_weight_fraction_leaf=0.0,
                           n_estimators=100, n_iter_no_change=None,
                           random_state=42, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

Meta model:

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=42, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)